### ISSUE TITLE
How to use flashy in ajax context with modal ?

### ISSUE THREAD

**Issue by faso-dev** [mercuryseries/flashy-bundle#1]
I have some button when i click on it, i open a modal to add new something, but after ajax json response, i want to display flashy message without need to reload the current page.

**Comment by mercuryseries** [comment]
You can use the flashy js function like `flashy("message")` or  `flashy("message", "https://mywebsite.com")`.

**Comment by faso-dev** [comment]
When i use it, i get flashy is not defined. My modal is in a _partials file and it rendered with json.
For example : my modal sumit data to a specific controller in Symfony, when transaction finished, i set ```$flasy->success('my message')``` and i return a json response with my modal form too.

**Comment by mercuryseries** [comment]
It's probably something specific to the way you are including flashy but I think that adding `window.flashy = flashy` in the place where the flashy js function is defined might help.

**Comment by faso-dev** [comment]
OK I'll try it. Thanks
