### ISSUE TITLE
Deprecation with Symfony 5.3.0.BETA2

### ISSUE THREAD

**Issue by mdeherder** [mercuryseries/flashy-bundle#3]
`Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "mercuryseries_flashy.symfony_session_store" service.`
Hide context    Show trace

> [▼
>   "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext {#1255 ▼
>     +count: 1
>     -severity: E_USER_DEPRECATED
>     trace: {▼
>       C:\Symfony\appcyel\vendor\symfony\dependency-injection\Compiler\ResolveReferencesToAliasesPass.php:68 {▼
>         Symfony\Component\DependencyInjection\Compiler\ResolveReferencesToAliasesPass->getDefinitionId(string $id, ContainerBuilder $container): string …
>         ›     $deprecation = $alias->getDeprecation($id);
>         ›     trigger_deprecation($deprecation['package'], $deprecation['version'], rtrim($deprecation['message'], '. ').'. It is being referenced by the "%s" '.($container->hasDefinition($this->currentId) ? 'service.' : 'alias.'), $this->currentId);
>         › }
>       }
>       C:\Symfony\appcyel\vendor\symfony\dependency-injection\Compiler\ResolveReferencesToAliasesPass.php:51 {▼
>         › 
>         › $defId = $this->getDefinitionId($id = (string) $value, $this->container);
>         › 
>       }
>     }
>   }
> ]

**Comment by mercuryseries** [comment]
Thanks @mdeherder. Issue solved ✅. A new version 4.0.0 has been published.
